adding bms to sidebar
hpcanalytics/documentation pull request #5
Opened 2019-06-14 15:46 UTC by supunkamburugamuve

2019-06-14 16:20 UTC, orbeckst requested changes
Thanks for adding the links to the BMS pages. This looks ok.

The PR also contains publication updates. I added some from ASU.

However, the link format appears to be restructured text while the file format is Markdown so most of the links need to be fixed. Furthermore, many links are [click here](https://www.w3.org/QA/Tips/noClickHere) type links that really should be changed to something that makes more sense semantically. I have examples in the PR that show what I mean.

2019-06-14 16:20 UTC, orbeckst commented on website/sidebars.json
> +    "Biomolecular Simulations": ["bms", "bms-cpptraj", "bms-mdanalysis", "bms-pmda", "bms-radical-cybertools"],
This looks good.

2019-06-14 16:20 UTC, orbeckst commented on docs/publications.md
> +   : hadoop-on-hpc `http://arxiv.org/abs/1602.00345
These are restructured text links but the format is markdown – needs to be changed.

2019-06-14 16:20 UTC, orbeckst commented on docs/publications.md
> +   `here <http://arxiv.org/pdf/1501.05041v1.pdf>`__
Link names that just say "here" are semantically awful. Make the link name appear as an identifier such as 
```markdown
... [arXiv: 1501.05041v1](http://arxiv.org/pdf/1501.05041v1.pdf) ...
```

2019-06-14 16:20 UTC, orbeckst commented on docs/publications.md
> +   `here <http://arxiv.org/abs/1403.1528>`__
avoid "here" links – see https://www.w3.org/QA/Tips/noClickHere

2019-06-14 16:20 UTC, orbeckst commented on docs/publications.md
> +   [10.1145/3225058.3225128](https://doi.org/10.1145/3225058.3225128)
example of a semantically sensible link

2019-06-21 08:27 UTC, orbeckst commented
@supunkamburugamuve let me know when you had time to work on the PR and I will review again.

2019-08-02 14:57 UTC, supunkamburugamuve commented on docs/publications.md
> +   [10.1145/3225058.3225128](https://doi.org/10.1145/3225058.3225128)
Added these changes

2019-08-02 15:02 UTC, orbeckst approved these changes

2019-08-02 15:03 UTC, orbeckst commented
@supunkamburugamuve thanks – please merge when you think you're ready

2019-08-02 15:04 UTC, merged